package main

import (
	"strings"
	"testing"
)

func TestFixSchemasBinaryFields(t *testing.T) {
	input := `// Code generated by ogen, DO NOT EDIT.
package api

type BodySpeechToTextV1SpeechToTextPostMultipart struct {
	// The file to transcribe.
	File OptNilString ` + "`" + `json:"file"` + "`" + `
	// The language code.
	LanguageCode OptNilString ` + "`" + `json:"language_code"` + "`" + `
}

type BodyOtherMultipart struct {
	// Another file field.
	File OptNilString ` + "`" + `json:"file"` + "`" + `
}

type BodySomeJSONRequest struct {
	// This should not be changed - not a Multipart struct.
	File OptNilString ` + "`" + `json:"file"` + "`" + `
}
`

	result, count := FixSchemasBinaryFields([]byte(input))

	if count != 2 {
		t.Errorf("Expected 2 fixes, got %d", count)
	}

	resultStr := string(result)

	// Check that Multipart struct File fields were fixed
	if !strings.Contains(resultStr, "type BodySpeechToTextV1SpeechToTextPostMultipart struct") {
		t.Error("Lost struct definition")
	}

	// Count OptMultipartFile occurrences in Multipart structs
	if strings.Count(resultStr, "File OptMultipartFile") != 2 {
		t.Errorf("Expected 2 OptMultipartFile, got %d", strings.Count(resultStr, "File OptMultipartFile"))
	}

	// Check that non-Multipart struct was NOT changed
	if !strings.Contains(resultStr, "type BodySomeJSONRequest struct {\n\t// This should not be changed") {
		t.Error("Non-Multipart struct definition lost")
	}
	if !strings.Contains(resultStr, "BodySomeJSONRequest") || strings.Contains(resultStr, "BodySomeJSONRequest") && !strings.Contains(resultStr, "File OptNilString `json:\"file\"`") {
		// This test is a bit complex - ensure the non-Multipart struct still has OptNilString
		jsonRequestIdx := strings.Index(resultStr, "type BodySomeJSONRequest struct")
		if jsonRequestIdx != -1 {
			// Find the File line after this struct
			afterStruct := resultStr[jsonRequestIdx:]
			closeBrace := strings.Index(afterStruct, "}")
			if closeBrace != -1 {
				structContent := afterStruct[:closeBrace]
				if !strings.Contains(structContent, "OptNilString") {
					t.Error("Non-Multipart struct should not be changed")
				}
			}
		}
	}
}

func TestFixSchemasBinaryFields_Idempotent(t *testing.T) {
	input := `type BodyTestMultipart struct {
	File OptMultipartFile ` + "`" + `json:"file"` + "`" + `
}
`
	result, count := FixSchemasBinaryFields([]byte(input))

	if count != 0 {
		t.Errorf("Expected 0 fixes on already-fixed content, got %d", count)
	}

	if string(result) != input {
		t.Error("Idempotent operation changed the content")
	}
}

func TestFixEncodersBinaryFields(t *testing.T) {
	input := `func encodeSpeechToTextRequest(
	req *BodySpeechToTextV1SpeechToTextPostMultipart,
	r *http.Request,
) error {
	const contentType = "multipart/form-data"
	request := req

	q := uri.NewFormEncoder(map[string]string{})
	{
		// Encode "file" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "file",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := request.File.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
		if err := q.WriteMultipart(w); err != nil {
			return errors.Wrap(err, "write multipart")
		}
		return nil
	})
	ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
	return nil
}

func encodeOtherRequest(
`

	result, count := FixEncodersBinaryFields([]byte(input))

	if count != 1 {
		t.Errorf("Expected 1 fix, got %d", count)
	}

	resultStr := string(result)

	// Check that the string-based encoding was removed
	if strings.Contains(resultStr, `Encode "file" form field`) {
		t.Error("String-based file encoding should be removed")
	}

	if strings.Contains(resultStr, "conv.StringToString(val)") {
		t.Error("String conversion should be removed")
	}

	// Check that WriteMultipart was added
	if !strings.Contains(resultStr, `val.WriteMultipart("file", w)`) {
		t.Error("WriteMultipart for file should be added")
	}

	// Check that it's inside CreateMultipartBody
	multipartStart := strings.Index(resultStr, "ht.CreateMultipartBody")
	writeFilePos := strings.Index(resultStr, `val.WriteMultipart("file", w)`)

	if writeFilePos < multipartStart {
		t.Error("WriteMultipart should be inside CreateMultipartBody")
	}
}

func TestFixEncodersBinaryFields_NoMatch(t *testing.T) {
	input := `func encodeSimpleRequest(
	req *SimpleRequest,
	r *http.Request,
) error {
	// No file field here
	return nil
}
`

	result, count := FixEncodersBinaryFields([]byte(input))

	if count != 0 {
		t.Errorf("Expected 0 fixes, got %d", count)
	}

	if string(result) != input {
		t.Error("Content should not change when there's nothing to fix")
	}
}
